  - id: data-enricher
    dependencies: key-finder
    stepName: Data parser step
    mainClass: com.company.namespace.DataEnricher
    config:
      recordClass: com.company.data.client.laborafax
      datasources:
        - name: debt
          location: /server/datasources/debt/         
